### ISSUE TITLE
If no "objective score" elements

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/class_feedback#2]
Currently if I remove all the objective score elements there are two bugs:

1) The e-mail still includes "Objective Score Elements:"
2) When I return to the page after saving, some objective score elements are added back in.  For example, I am seeing one called `textEnd`.

**Comment by Yen168** [comment]
Fixed. I also saw textStart lol.

**Comment by Yen168** [comment]
Fixed. I also saw textStart lol.
