### ISSUE TITLE
"Saved" message is unclear

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/class_feedback#4]
Currently, after you save, it says:

> All data are restored in server!

The word "restored" here is confusing, something simple like the following might be better:

> All feedback saved.

(Eventually, having it save automatically in an "AJAX" fashion might be best.)

**Comment by Yen168** [comment]
Hello, The app uses AJAX to save input automatically. It use jQuery .change() function.  The "save all" button is smart-proofing by default design. I will update the sentence to "All feedback saved".

Thank you for those valuable feedback!

**Comment by Yen168** [comment]
Text Updated.
